[tool.poetry]
name = "ml-ops-wildlife"
version = "0.1.0"
description = ""
authors = ["Mihai Anca <mihai.anca13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
